### ISSUE TITLE
Lack of components should be identified

### ISSUE THREAD

**Issue by karnan4ever** [Tendrl/dashboard#12]
What ever components that are in UXD should be available in patternfly's release.
We were delayed by Datetime component, which is released very late. so, when ever a feature(page) is started, we should make sure that existing components are already there. we faced same issue with vertical navigation also.

**Comment by julienlim** [comment]
@karnan4ever - Ideally if we identify which components we would like from PatternFly in enough time, we should be able to ask the PatternFly team/community to provide the component, but likely we'll need at least 4 weeks heads-up as PatternFly sprints don't align with Tendrl sprints and in order to get it into their backlog.
