### ISSUE TITLE
Create File Share

### ISSUE THREAD

**Issue by gnehapk** [Tendrl/dashboard#190]

**Comment by julienlim** [comment]
@gnehapk @nnDarshan @brainfunked @mcarrano @japplewhite 

In reviewing comments on the Create File Share UX design (https://redhat.invisionapp.com/share/Q78YMAVDJ#/screens/217726640), there were comments that we need to ask user to input the # of replica sets (in the case of distributed replicated volume type) or # of subvolumes (in the case of distributed dispersed / EC volume type).

In thinking about this and looking at the gluster CLI, the user today never has to specify the replica set or subvolumes, so why should we make user do this in the UI.  It is not expected behavior.  Note: we did this in the past (old Gluster console) to reduce some of the business logic implementation work.

To be more specific, here are the CLI commands to create the volumes for the 2 different volume types:

Distributed Replicate CLI command/example (4-node distributed replicated volume with a 2-way mirror):
# gluster volume create test-volume replica 2 transport tcp server1:/brick1 server2:/brick2 server3:/brick3 server4:/brick4

Distributed Dispersed CLI command:
# gluster volume create disperse <count> [redundancy <count>] [transport tcp | rdma | tcp,rdma] [list of bricks]

Thus, IMHO, Tendrl should automatically determine the replica sets / subvolumes based on the volume type and # of nodes in the Gluster trusted storage pool.

Additionally, Tendrl needs to include business or validation logic to ensure the following in bricks being used in the replica set / subvolumes -- this includes and is not limited to the following:
* For distributed replicated, ensure replica set members (bricks) are not placed on the same node
* For distributed replicated, an even number of bricks must be used
* For distributed replicated, the number of bricks in a volume must be must be multiple of the replica count (2 or 3 depending on 2-way or 3-way distributed replicated)
* Minimum number of bricks gets derived based on replica count and number of nodes in the Gluster trusted storage pool.
     - If 2-way, 4 nodes, then # bricks min is 2
     - If 2-way, 6 nodes, then # bricks min is 6
     - If 3-way, 6 nodes, then # bricks min is 6
* For EC (distributed dispersed), refer to https://access.redhat.com/documentation/en-US/Red_Hat_Storage/3.1/html/Administration_Guide/chap-Recommended-Configuration_Dispersed.html to derive the rules needed.

Also note that we should look at the old Gluster console and Heketi for the logic as this has already been implemented previously.

Note: The ideal user flow in the UI for setting up a volume would be as follows:
* user picks volume type (along with specifying other volume attributes, e.g. volume name, cluster if not known, protocols, etc.)
* user picks bricks to use
* System (Tendrl) automatically distributes bricks into replica sets / subvolumes and ensures sufficient # bricks are satisfied and properly distributed between the replica sets / sub volumes, and shows/previews them to the user the layout and lets user know when additional bricks are required (if insufficient bricks selected), insufficient diversity of bricks (if bricks are not coming from all the different nodes), etc.

**Comment by fbalak** [comment]
@julienlim I think that automatic specification of parameters for gluster volume creation is a great feature but only as a default setting in a volume creation form. From this text it isn't clear to me if you want to hide majority of settings for volume creation away from user entirely. Also restrictions for number of bricks is a great thing but maybe it would be good if there was some global setting or a checkbox in the form that allows user to try unsupported configurations.

**Comment by nnDarshan** [comment]
@mcarrano  @julienlim  The reason its not needed in cli is, user would be providing the brick in multiples of replica count or in multiples of 6/11/12 (in case of EC). If not given in multiples cli refuses to create volume.

But in case of UI as portrayed in: https://redhat.invisionapp.com/share/Q78YMAVDJ#/screens/217726637 and https://redhat.invisionapp.com/share/Q78YMAVDJ#/screens/217726637. UI code needs to show buckets of replica sets or sub volumes, where user drops individual bricks... If user provides # replica sets or # subvolumes before hand, UI can clearly have those many # of buckets...Without this number UI will have to either show a long list of buckets or limit the number of buckets to 2 and show new buckets as and when user fills available buckets.
Please provide your thoughts

**Comment by nnDarshan** [comment]
@julienlim In the validation logic that is mentioned in https://github.com/Tendrl/dashboard/issues/190#issuecomment-285788853. Second bullet says "For distributed replicated, an even number of bricks must be used". But in case of 3way replicated volume with 3 replica sets, the total bricks needed is 9 right ?

**Comment by gnehapk** [comment]
@julienlim Can you please elaborate bullet 4?

**Comment by julienlim** [comment]
@gnehapk @nnDarshan @brainfunked @mcarrano @japplewhite @fbalak 

In the CLI (and heketi), the replica sets and subvolumes are derived automatically by Gluster based on the # of bricks being used an # replicas.

For example, replica set = # bricks / # replicas, and the resulting number cannot be a fraction.

Per Ben England, in a Gluster volume, DHT uses replica sets as subvolumes, so the more replica sets in a DHT volume, the more throughput you can achieve.  

Asking a user to specify replica sets (or subvolumes) is probably not a good thing as it could potentially reduce throughput if user opts for a lower number unless we tell users how to correctly calculate the value of replica sets / subvolumes themselves. 

So here are a few ways to address this in the UI:
(1) Allow user to specify # Replica Sets / # Subvolumes, and hope user knows how to calculate this.  This avoids System having to perform this calculation but can potentially lead to poor Gluster (throughput) performance.  Note: We should provide adequate guidance, i.e. infotip and/or documentation, on how to do so.  If we go down this route, then defaulting to 2 makes sense and we somehow need users to adjust this to avoid performance penalties.

(2) Match the Gluster CLI in that user specifies # bricks, and System generates the Replica sets / subvolumes automatically, and System will "intelligently" distribute the bricks to the replica set / subvolume aligned with best practices (e.g. bricks in the replica set not from the same node).

(3) Allow user to specify # Bricks per Replica Sets / # Bricks per Subvolumes, and hope user knows how to calculate this.  This avoids System having to perform this calculation but can potentially lead to poor Gluster (throughput) performance.  Note: We should provide adequate guidance, i.e. infotip and/or documentation, on how to do so.  I believe this is what was done previously in the old Gluster console.

In all approaches, System will need to validate against best practices and flag issues for user to resolve (e.g. insufficient bricks, insufficient distribution amongst the nodes, multiples of replica count or in multiples of 6/11/12 (in case of EC), etc.)

I still lean towards Approach #2, and we can adjust the design accordingly.  Thoughts?

=====

@nnDarshan - Refering to "@julienlim In the validation logic that is mentioned in #190 (comment). Second bullet says "For distributed replicated, an even number of bricks must be used". But in case of 3way replicated volume with 3 replica sets, the total bricks needed is 9 right ?"

For distribute replicated, it always have to be in multiples of the # of replicas.  If you plan to have 3 replicas and 9 bricks, then the replica set is as follows:
   replica set = # bricks / # replicas 
                     = 9 / 3
                     = 3

"For distributed replicated, an even number of bricks must be used" statement is not correct (I was thinking of an example when I wrote that statement, and thank you for your attention to detail.

**Comment by zeichenanonym** [comment]
IMO the best approach is already implemented by Heketi:

- Only provide the information necessary (replica count, EC profile)
- Let "the system" decide which bricks to use based on the information provided
- **Additionally:** Leverage our GUI advantage over Console and display which bricks on hosts we use

IMO we should not ask the user to list each single brick manually that should be used for the storage. In my experience a lot of users have only 1-3 volumes in a storage pool and always use all bricks for all volumes.

**Comment by mbukatov** [comment]
@cloudbehl Could you sum up the state of this issue? I mean, short description of what one can take away from this. Thank you.
