### ISSUE TITLE
Create Pool workflow: replicas field should not show when EC selected

### ISSUE THREAD

**Issue by julienlim** [Tendrl/dashboard#237]
@cloudbehl @gnehapk 

For the Create Pool workflow, if user selects EC and 2+1, why do we still see the Replicas field?  Replicas is only applicable when Standard/Replicated is selected.

**Comment by cloudbehl** [comment]
@julienlim @sankarshanmukhopadhyay I Just had a look at the create pool workflow and saw the UX[1] for EC type. I can see the replicas field being there EC pool UX design[1]. That's why it has been implemented in the UI. 

@julienlim @mcarrano Please confirm that replicas field needs it to be removed from UI.

[1].https://redhat.invisionapp.com/share/2T9LPMEEB#/screens/209774648

**Comment by mcarrano** [comment]
Yes, that's an error in the design.  I will correct it and repost.  But yes, when the user changes the Type to Erasure Coded, the Replicas field should be hidden.

**Comment by cloudbehl** [comment]
@julienlim @Tendrl/qe The bug is fixed from UI team. Please verify on the new build[1] available.

[1]. tendrl-dashboard-1.2.1-04_17_2017_17_24_12.noarch.rpm

**Comment by nthomas-redhat** [comment]
Closing this as this is already fixed
