### ISSUE TITLE
Issue while displaying Pool quota as percentage in pool list page.

### ISSUE THREAD

**Issue by cloudbehl** [Tendrl/dashboard#416]
We set two value in pool quota while creating a pool.
1) Quota Max Bytes
2) Quota Max Objects.

Quota Max Bytes: The quota Max bytes is a percentage Number which is set while creating a pool. The percentage number will out of the total utilization available in the Host/Node and while sending the max bytes in post data we convert that percentage number to bytes by using this formula[1].  
(utilizationAvailable/100)*percentageNumber(That user has set)

Problem: In pool List view we have to show a pool max bytes as a percentage but the API/Backend is providing value in bytes. So while showing we need to convert it back into a percentage. But this time the percentage is coming wrong because the value of available utilization getting changed every time.

Example: So let's suppose creating a pool we have total 10GB of space available and the user has selected max Quota bytes as 50% that means 5GB and user have created a Pool. But when the user goes back to see in the pool list it shows as 55%(based upon how the available utilization has changed) max quota value. This difference is coming because the Available utilization can change over time.

@shtripat @nthomas-redhat @r0h4n @julienlim

**Comment by cloudbehl** [comment]
@julienlim can you please have a look. As this(https://bugzilla.redhat.com/show_bug.cgi?id=1455576) Issue is blocked.

**Comment by julienlim** [comment]
@shtripat @nthomas-redhat @r0h4n @jcloudbehl @Tendrl/qe 

Pool quota should be calculated from total_bytes and not total_avail_bytes.

**Comment by julienlim** [comment]
@shtripat @nthomas-redhat @r0h4n @jcloudbehl @Tendrl/qe @mcarrano @japplewhite 

From looking at https://redhat.invisionapp.com/share/2T9LPMEEB#/screens/217733677, I see why you're using total_avail_bytes.

My recommendation then is to not show the calculated amount in the UI, and that should eliminate the UX issue you mention of causing the incorrect % shown after the fact since total_bytes is not really available till after the pool is provisioned.

Fundamentally, after pool is provisioned or created, the pool is then set at the cacculated 50% for quota, and at that point, it should hopefully show up correctly in the list view.

There's a couple things to consider from a UX perspective is that the % probably can change over time because of how Ceph works, whereby the quota is set based quota_bytes, and over time if the pool expands, that % will change (decrease) and potentially lead to confusion to the user, which means we probably need to either change the representation (to n-bytes) in the list views and other views, OR to document that the quota % is the initially set quota and may decrease over time when the pools are expanded.

There are a few options
(1) change it in UI to only setting in on a n-byte basis and also see quota in the n-byte basis
(2) document that quota % may change over time and better label it as the initial quota set based on %.
(3) same as (2) but in list views and other places (after initial quota configuration), only show it as n-byte

My gut is to go with (3) as to have a user enter in n-bytes will be hard (hence why the %).

**Comment by julienlim** [comment]
@shtripat @nthomas-redhat @r0h4n @jcloudbehl @Tendrl/qe @mcarrano @japplewhite

Here's where it ended up:
- Setting quota for max-bytes still based on %, but have added some helper text to help clarify that it is still set by max-bytes.

For reporting purposes (e.g. list views, object details, etc.), it will show both n-bytes (%).

Updates have been made to the design to reflect this recommendation:
- Create Pool (Quotas)
- Create RBD (Select Backing Pool - Use Existing Pool)
- Edit Pool - General configuration
- Pools List View

All designs and related updates can be linked from https://github.com/Tendrl/ui/blob/master/UI%20Designs.adoc.

**Comment by brainfunked** [comment]
According to the [ceph documentation on quotas](http://docs.ceph.com/docs/master/rados/operations/pools/#set-pool-quotas), the quota can only be set as either maximum number of bytes or objects per pool. Tendrl must be consistent with the documentation. Users must be able to refer to the storage system documentation and apply the knowledge directly in Tendrl. If any information is required to be displayed to allow the user to make an informed decision, we should displayed.
