### ISSUE TITLE
Create ceph cluster offers one host but forces choice between mon and osd

### ISSUE THREAD

**Issue by japplewhite** [Tendrl/dashboard#447]
If we offer one host for POC mode it should be a combined mon + osd node in the drop down. There is no way to do a 1 node ceph cluster unless we do this.

**Comment by sankarshanmukhopadhyay** [comment]
@Tendrl/tendrl-core - how does the backend manage and handle the PoC mode?

**Comment by r0h4n** [comment]
The backend assigns tags "ceph/mon" or "ceph/osd"  if it detects a mon or osd service running. So if a single node has a mon and/or osd service running, the node will be tagged accordingly.

I guess the UI has to start supporting multiple tags like the backend does (cc @cloudbehl )

**Comment by cloudbehl** [comment]
@r0h4n As per the UX there is an option of setting the node as mon + osd is available. But in UI we have not implemented that option. So I think @japplewhite is asking for that option.

@brainfunked @nthomas-redhat Should UI go ahead and implement this option(mon+osd)? Because I remember there was a discussion around it, for implementation of this option(mon+osd) in UI.

**Comment by r0h4n** [comment]
Let's revisit this when we support CreateCluster
