### ISSUE TITLE
Donut and Sparkline Chart Component

### ISSUE THREAD

**Issue by gnehapk** [Tendrl/dashboard#67]

**Comment by kamleshverma1** [comment]
Generally , We should have one common component for draw the charts (donut or sparkline chart) as shown in UX design. ( https://redhat.invisionapp.com/share/BR8JDCGSQ#/screens/185937524 )

**Library used** : We used c3js chart (http://c3js.org/) libaray . and using "angular patternfly" (http://angular-patternfly.rhcloud.com/) as wrapper in order to access c3 chart features in angularjs application.

**How to use donut chart**:  We are going to create "angular directive" for donut chart component in order to draw "donut chart". and directive name will be "donutChart" and it will support the following 
parameters.

**chartId**: Expected "unique number" for each chart in one template.
                For example: if you are using ng-repeat .
                 ```
                <div ng-repeat="host in hostList">
                    <donut-chart chart-id="{{$index}}">
                    </donut-chart>
                </div>
                 ```
                NOTE: "c3" (plugin used for draw chart) expect unique id for each chart

**chartTitle (optional)**:  Expected a string for title.
        NOTE:-  In UX design some of the place "title" is not there. so it should be optional.
(https://redhat.invisionapp.com/share/BR8JDCGSQ#/screens/198417118 ).

**chartData**: Should be object with two parameters - total and used.
        Example: -
        (In controller):
        vm.chartData = {"used":352460800,"total":3524608000} (defined chartData object)
       (In template):
         ```
        <div ng-repeat="host in hostList">
            <donut-chart chart-id="{{$index}}" chart-data="chartData">
            </donut-chart>
        </div>
        ```
        NOTE: if "vm.chartData.total" is zero . than automatically "donut chart" will show "no data available".

**chartThresholds (optional)** :  If user will not pass thresholds value as parameter than it will have default value:  {'warning':'60','error':'90'} which should be defined in "config.json". because it should be configurable
        (In controller):
        vm.chartThresholds = {'warning':'40','error':'90'}; (defined chartThresholds object)
        (In your template):
         ```
        <div ng-repeat="host in hostList">
            <donut-chart chart-id="{{$index}}" chart-thresholds="chartThresholds">
            </donut-chart>
        </div>
        ```
